In [48]:
import numpy as np
a = np.array(1,ndmin = 0)
b = np.array([0,1,2,3] , ndmin = 1)
c = np.array([[10,11,12],[13,14,15]],ndmin=2)
d = np.array([0],ndmin=3)

In [49]:
print(a)
print(b)
print(c)
d

1
[0 1 2 3]
[[10 11 12]
 [13 14 15]]


array([[[0]]])

In [50]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
d.ndim

0
1
2


3