In [17]:
import numpy as np
arr = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
print(arr[1:7])
print(arr[6:1:-2])
print(arr[3::2])
print(arr[7])
arr

[102 103 104 105 106 107]
[107 105 103]
[104 106 108 110]
108


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [18]:
#matric 10*10
matric = np.random.randint(1, 10, (10, 10))

print(matric)


[[2 2 2 3 5 8 6 8 1 4]
 [4 5 7 4 5 4 4 8 5 5]
 [3 6 3 4 5 6 6 7 6 8]
 [7 2 1 3 6 8 9 9 5 5]
 [8 1 6 2 7 2 1 2 3 8]
 [6 3 6 2 3 4 5 6 2 2]
 [9 1 3 4 5 2 3 1 6 1]
 [3 3 5 9 2 5 2 6 9 6]
 [7 3 7 8 7 7 7 1 6 6]
 [4 6 5 8 5 8 6 5 6 7]]


In [19]:
print (matric[0:4,0:4])

[[2 2 2 3]
 [4 5 7 4]
 [3 6 3 4]
 [7 2 1 3]]


In [20]:
print (matric[0:5,5:])

[[8 6 8 1 4]
 [4 4 8 5 5]
 [6 6 7 6 8]
 [8 9 9 5 5]
 [2 1 2 3 8]]


In [21]:
print (matric[4:,0:4])

[[8 1 6 2]
 [6 3 6 2]
 [9 1 3 4]
 [3 3 5 9]
 [7 3 7 8]
 [4 6 5 8]]


In [22]:
print (matric[5:,5:])

[[4 5 6 2 2]
 [2 3 1 6 1]
 [5 2 6 9 6]
 [7 7 1 6 6]
 [8 6 5 6 7]]


In [23]:
print (matric[3:6,3:6])

[[3 6 8]
 [2 7 2]
 [2 3 4]]


In [24]:
#matric 1000*1000
matric = np.random.randint(1000, size=(1000, 1000))
print(matric)

[[875 451 208 ... 491 335 402]
 [299 878  10 ... 512 438 781]
 [165 709 715 ... 461 591 560]
 ...
 [606 375 737 ... 933 869 235]
 [577 817 118 ...  29 822  38]
 [803 209 947 ...  89 637 981]]
